version: '3'

services:
  postgresrv:
    image: postgres:latest
    environment:
      POSTGRES_DB: spring_cloud_project_store_dev
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cHJvbWV0aGV1cw==}
    ports:
      - "5432:5432"
    volumes:
      - C:\\Users\\weverton.souza\\Documents\\enviroment_two\data-base\\spring-cloud-project\\postgresql:/var/lib/postgres
    networks:
      - spring-cloud-network

  phpmyadmin:
    image: dpage/pgadmin4
    links:
      - postgresrv
    ports:
      - 5000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - postgresrv
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
