version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: prometheus_project_dev
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cHJvbWV0aGV1cw==}
    ports:
      - "5434:5432"
    volumes:
      - .\\postgres:/var/lib/postgres
    networks:
      - prometheus-project-network

  phpmyadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - postgres
    networks:
      - prometheus-project-network

networks:
  prometheus-project-network:
    driver: bridge
