server:
  port: 8500
  servlet:
    context-path: /v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_cloud_project_store
    username: postgres
    password: cHJvbWV0aGV1cw==
    driver-class-name: org.postgresql.Driver
